name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'osztalypenz-app/**'

jobs:
  build-frontend:
    if: "contains(github.event.head_commit.message, 'osztalypenz-app') || github.event.paths_any == 'osztalypenz-app/**'"
    runs-on: ubuntu-latest
    environment: osztalypenz
    name: Build and Push Frontend Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./osztalypenz-app
          file: ./osztalypenz-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/osztalypenz_frontend:latest

  build-backend:
    if: "contains(github.event.head_commit.message, 'backend') || github.event.paths_any == 'backend/**'"
    runs-on: ubuntu-latest
    environment: osztalypenz
    name: Build and Push Backend Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/osztalypenz_backend:latest
