name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'osztalypenz-app/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    environment: osztalypenz
    name: Build and Push Frontend Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./osztalypenz-app
          file: ./osztalypenz-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/osztalypenz_frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    environment: osztalypenz
    name: Build and Push Backend Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/osztalypenz_backend:latest

run-server-script:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    name: SSH into Server and Run Reload Script

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run reload_images.sh on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 80.211.204.17
          username: dani
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/osztalypenz_project/test
            ./reload_images.sh
