jobs:
  build-frontend:
    runs-on: ubuntu-latest
    environment: osztalypenz
    name: Build and Push Frontend Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: tag
        run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)"

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./osztalypenz-app
          file: ./osztalypenz-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/osztalypenz_frontend:${{ steps.tag.outputs.tag }}

  build-backend:
    runs-on: ubuntu-latest
    environment: osztalypenz
    name: Build and Push Backend Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: tag
        run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)"

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/osztalypenz_backend:${{ steps.tag.outputs.tag }}
